### ISSUE TITLE
Can not find RecordHandlers using Java dependency

### ISSUE THREAD

**Issue by ivangreene** [wix/greyhound#160]
When using this Maven dependency declaration:
```xml
    <dependency>
      <groupId>com.wix</groupId>
      <artifactId>greyhound-java</artifactId>
      <version>0.0.5</version>
    </dependency>
```
I cannot find the class [RecordHandlers](https://github.com/wix/greyhound/blob/master/java-interop/src/main/java/com/wixpress/dst/greyhound/java/RecordHandlers.java) anywhere in the jars it pulls down

**Comment by natansil** [comment]
Found the cause and fixed it [here](https://github.com/wix/greyhound/pull/161/commits/3cab7be081f93b3133c4526b4be222410a7284fa)
Sorry about that.
Will publish a new version to Maven ASAP.
Thank you so much for reporting!

**Comment by natansil** [comment]
the new version is out:
https://search.maven.org/artifact/com.wix/greyhound-java/0.1.0/jar
@ivangreene please verify the issue is gone on your end

**Comment by ivangreene** [comment]
@natansil yep, can now find this class, and the rest of the Java classes are no longer compiled as scala (not sure what happened there, but for example the interface `RecordHandler` was defined as a trait, but is now appearing as a regular interface and easier to read.) Thanks for the quick response

**Comment by natansil** [comment]
> not sure what happened there
the bazel build target for the greyhound-java jar was `scala_library` by mistake.
`scala_library` emits two jars - scala jar (compiled by scalac) and a java jar (compiled by javac). and the publishing target took the scala one...
