### ISSUE TITLE
[Java SDK] How to configure a consumer with retry policy?

### ISSUE THREAD

**Issue by ankurgoel92** [wix/greyhound#247]
Can you please let me know how to configure a retry policy for a GreyhoundConsumer **in java**?

currently testing with below version:
```
<dependency>
    <groupId>com.wix</groupId>
     <artifactId>greyhound-java</artifactId>
      <version>0.1.3</version>
 </dependency>
```

Cannot find the below methods:
``` 
ConsumeRetryPolicy.aRetryPolicy(....)
GreyhoundConsumer.aGrehoundConsumerSpec(...).withGroup(..).withRetryPolicy(...)

**Comment by natansil** [comment]
Hi @ankurgoel92,
RetryPolicy is currently missing in Java API.
But now that you've opened an issue, we will increase this task priority.
I will update here when a new version with retry policy will be ready.

Thanks and sorry for this.

**Comment by ankurgoel92** [comment]
Thanks a lot @natansil. I will wait for the update.

**Comment by natansil** [comment]
@ankurgoel92. I'm glad to report that retry policies were added for GreyhoundConsumer in java.
https://github.com/wix/greyhound/commit/71088bd501e8f7d45119a8b416d051dcadcbeb5d
https://github.com/wix/greyhound/commit/7e7bfedcf190f10dad5c09587f84484cc0ef4384
I've published version 0.1.4 that includes these changes.

Thank you @antonkrapivner for working on this 🙏

**Comment by ankurgoel92** [comment]
Thanks a lot. Will give this a go.

**Comment by natansil** [comment]
Great! Feel free to provide any feedback you want
