### ISSUE TITLE
Upgrade to latest graknlabs/bazel-distribution dep

### ISSUE THREAD

**Issue by paul-hammant** [wix/greyhound#281]
https://github.com/graknlabs/bazel-distribution has moved forward since the pinned revision (May 2020).

`@graknlabs_bazel_distribution//maven/templates:rules.bzl` is now `@graknlabs_bazel_distribution//maven:rules.bzl`

There are other changes to the attribute names for deploy_maven rule.

**Comment by natansil** [comment]
upgraded to vaticle
https://github.com/vaticle/bazel-distribution
