### ISSUE TITLE
Any example for connecting to secure Kafka (SSL)

### ISSUE THREAD

**Issue by b41somp** [wix/greyhound#299]
I can't see example to setup connection to secure Kafka (SSL). Any example?

**Comment by natansil** [comment]
Hi @b41somp,

**Which API are you using** `Java`, `Scala Future`, or `Scala ZIO`?
It seems that currently setting up SSL is a missing feature from `Java `and `Scala Future`.

What's missing is the option to provide custom properties. `GreyhoundConfig` only has `bootstrapServers`

In terms of the actual properties needed for SSL please refer to Kafka documentation for how t configure SSL [for producer and consumer](http://kafka.apache.org/documentation/#security_configclients)

**Comment by b41somp** [comment]
I am using Java library. Yes, I see in GreyhoundConfig, it accepts bootstrapServers string or Set but it doesn't use anything in the Set object except bootstrapServers string. I need a way to set kafka SSL properties as in Kafka documentation. Can I?

**Comment by natansil** [comment]
It's currently missing. We will make an effort to add this ability soon.
I will update here when this happens.

btw, do you want to try to contribute this? I will guide you of course...

**Comment by b41somp** [comment]
I have only limited knowledge about Scala but I think the modification should be around a few classes, right? Yes, please guide me.

**Comment by natansil** [comment]
Thank you so much!
Advanced Scala knowledge is not needed indeed.

So we have [GreyhoundConfig](https://github.com/wix/greyhound/blob/master/java-interop/src/main/java/com/wixpress/dst/greyhound/scala/GreyhoundConfig.scala#L9-L10) object.

It is missing 
```scala
extraProperties: Map[String, String] = Map.empty,
```

and another  constructor that accepts `bootstrapServers` and `extraProperties`, similar to:
```scala
  def this(bootstrapServers: String) =
    this(bootstrapServers, GreyhoundRuntime.Live)
```
    
in order for the user to avoid the need to pass a `GreyhoundRuntime` by themselves.


Next in  `GreyhoundConsumersBuilder` you need to pass `extraProperties` to the underlying `RecordConsumer`'s `RecordConsumerConfig` - [link](https://github.com/wix/greyhound/blob/master/java-interop/src/main/java/com/wixpress/dst/greyhound/scala/GreyhoundConsumersBuilder.scala#L33)

In terms of tests,
we have regular junit `GreyhoundBuilderTest`.

you can add another test case for 
```java 
@Test
public void consumer_config_with_custom_props() throws Exception {
```
testing ssl custom_props will require that the embedded kafka broker will allow ssl connections, which is too much hassle,
but maybe a simpler prop can be tests like `fetch.min.bytes` and then you can test that only once you produce enough bytes, does a response return, or maybe you have a better idea...


let's talk about producer side afterwards, but should be very similar...

Thanks again @b41somp.
We highly appreciate it!

**Comment by natansil** [comment]
If you don't want to install bazel build tool locally, you can just push to **PR** and have _github actions_ check your changes for you...

**Comment by b41somp** [comment]
I can setup, build and test with bazel in my IDEA now. My modification is centred around `GreyhoundConsumer` and `GreyhoundConsumersBuilder`. It would be like setting `OffsetReset` and `RetryConfig`, etc. in `GreyhoundConsumer.scala` so will add `withExtraProperties` method into `GreyhoundConsumer.scala` as in below:

`
  def withExtraproperties(extraProperties: java.util.Map[String, String]) =
    copy(extraProperties = extraProperties.asScala.toMap)
`

Then I will modify `GreyhoundConsumersBuilder` accordingly to pass `extraProperties` to `RecordConsumerConfig` class. 

What do you think?

**Comment by b41somp** [comment]
Sorry, I forget about the producer. Since it is using `GreyhoundConfig` as do with the consumer, so I am thinking about to modify `GreyhoundConfig` class.

**Comment by natansil** [comment]
> I can setup, build and test with bazel in my IDEA now.

wonderful

`Sorry, I forget about the producer. Since it is using GreyhoundConfig as do with the consumer, so I am thinking about to modify GreyhoundConfig class.`

I think both are relevant, where consumer/producer config props will take precedence over GreyhoundConfig props. WDYT?

**Comment by natansil** [comment]
It would be easiest to add to GreyhoundConfig for sure.

**Comment by b41somp** [comment]
I have created the pull request - #301  but my test case is still failing even I set the kafka timeout properties to max value. Can you help to review and verify it?

**Comment by natansil** [comment]
commented in #301

**Comment by natansil** [comment]
PR is merged.
@b41somp Thank you so much for your great contribution to Greyhound!

new version 0.1.5 was cut.
https://repo1.maven.org/maven2/com/wix/greyhound-java/0.1.5/
https://oss.sonatype.org/content/groups/public/com/wix/greyhound-java/0.1.5/
It will take a bit more time to get the version in the official host https://search.maven.org/search?q=greyhound

Please try it out, we would appreciate any feedback.

**Comment by natansil** [comment]
@b41somp is this version OK for you? Can I close this issue?
