### ISSUE TITLE
Is com.wixpress.dst.greyhound.testkit published somewhere?

### ISSUE THREAD

**Issue by jpablo** [wix/greyhound#324]
Hi, I was just following the tutorial, where at the end this line is mentioned

```
import com.wixpress.dst.greyhound.testkit._
```

But it looks like this is not published in maven. 

What is the recommended way to access this library?

**Comment by natansil** [comment]
Hi @jpablo,

I apologise for the late reply.
I added `greyhound-testkit` jar to our publishing flow to Maven Central.
Here is the [link](https://oss.sonatype.org/content/groups/public/com/wix/greyhound-testkit_2.12/) to it on Sonatype.
Please allow a few hours for it to be copied to all mirrors, including the one you are using.

We would highly appreciate any feedback you may have on the testkit :)
