### ISSUE TITLE
[Question] Blocking retry dashboard

### ISSUE THREAD

**Issue by Satya758** [wix/greyhound#408]
Hi,

In video sessions of Greyhound, there is an information about a dashboard to skip the blocked message or identify the block in consumption.

![image](https://user-images.githubusercontent.com/6910439/125049284-710cbb80-e0be-11eb-9015-593d95aecf26.png)

Is this part of an open source project? If not, is there a way to extract this information from Greyhound?

Thanks
Satya

**Comment by natansil** [comment]
Hi @Satya758 ,

The dashboard about blocked messages is an internal _wix backoffice app_ (which is quite tricky to open-source) that makes it easier for Wix developers to monitor and debug production. there is a standard `grpc` endpoint that all services expose and that in turn call Greyhound api to get the relevant information. e.g. _blocked messages_.

The Greyhound RecordConsumer api for production debugging is called `state` and it looks like [this](https://github.com/wix/greyhound/blob/master/core/src/main/scala/com/wixpress/dst/greyhound/core/consumer/RecordConsumer.scala#L103-L106). (Unfortunately it is currently only available in the Scala-ZIO API I linked.)

Which API are you using? It can actually be quite easy to add this capability to java API [here](https://github.com/wix/greyhound/blob/master/java-interop/src/main/java/com/wixpress/dst/greyhound/java/GreyhoundConsumers.java#L3) in `GreyhoundConsumers` interface.

I will add this task (_expose state in java api GreyhoundConsumers_) to our backlog. If you want to speed things up and contribute, I will gladly assist in guiding you on how to do this.

**Comment by Satya758** [comment]
Hi @natansil 

Thanks for the tip, We are using Scala ZIO API, I will have a look into it.

Thanks
