### ISSUE TITLE
PRs cannot auto mere

### ISSUE THREAD

**Issue by natansil** [wix/greyhound#41]
We have a service at Wix that merges (rebases) PR once status checks have passed via github api:
but github api returns `pending` even when check has passed (e.g. https://github.com/wix/greyhound/pull/40)

@fkorotkov can you please help us understand how to fix this

**Comment by natansil** [comment]
The developer in charge of this service wrote:
https://developer.github.com/v3/repos/branches/#list-required-status-checks-contexts-of-protected-branch - returns Cirrus CI/main but once i'm asking the state i got pending with empty list of statuses

**Comment by fkorotkov** [comment]
Seems you are using commit statuses but should use check suites: https://developer.github.com/apps/

You can take a look how a similar check is implemented in Submit Queue App: https://github.com/cirruslabs/gh-submit-queue

**Comment by natansil** [comment]
Thank you for the quick reply!
CC: @eliorh

**Comment by natansil** [comment]
Resolved by @eliorh
