### ISSUE TITLE
ZIO 2.x migration?

### ISSUE THREAD

**Issue by exp0nge** [wix/greyhound#445]
Are there plans to support ZIO 2.x? https://zio.dev/next/howto/migrate/zio-2.x-migration-guide/

One of the issues:

```
java.lang.NoClassDefFoundError: zio/Has$
        at com.wixpress.dst.greyhound.future.GreyhoundRuntime$.<init>(GreyhoundRuntime.scala:25)
        at com.wixpress.dst.greyhound.future.GreyhoundRuntime$.<clinit>(GreyhoundRuntime.scala)
```

**Comment by leonbur** [comment]
There are some internal discussions about ZIO 2.0. However since it's not GA yet, talking about timelines is moot at this point.

**Comment by natansil** [comment]
are you currently using ZIO 1.0 greyhound?
I think it would be hard to support both 1.0 and 2.0 by greyhound...

**Comment by exp0nge** [comment]
> are you currently using ZIO 1.0 greyhound? I think it would be hard to support both 1.0 and 2.0 by greyhound...

Nope, we are using 2.0


We have a monorepo so not possible to undo that decision to use 2.x

**Comment by natansil** [comment]
same for us. we will migrate between first GA and first patch version...

**Comment by rbraley** [comment]
This is blocking us from using greyhound in our monorepo as well, since we have some 2.x zio elsewhere. Glad to hear this is a priority for you folks as well @natansil

**Comment by rbraley** [comment]
Zio 2.0 is GA now, yay!

**Comment by natansil** [comment]
yep. we are in the process of migrating our private code base to ZIO 2.0
once that process is merged, the changes will automatically sync to public code.
No concrete ETA, but this is a high priority for us

**Comment by exp0nge** [comment]
Hi @natansil, any chance there's an update? 😃

**Comment by natansil** [comment]
@exp0nge I'm so sorry for the delay.
We had issues with several ZIO versions, but we are happy with the stability and perfomance of zio 2.0.5
I've published a new version to maven-central for greyhound 0.3.1 which we depends on zio 2.0.5.
