### ISSUE TITLE
Error in assemble_maven: assemble_maven rule 'sharedlibrary' in package 'sharedlibrary' conflicts with existing java_library rule

### ISSUE THREAD

**Issue by yeshamavani** [wix/greyhound#549]
Hello 
I am trying to publish a maven artifact to maven central using the https://github.com/vaticle/bazel-distribution/tree/master/maven  the way you are doing it here 
the difference is I have a java_library instead of scala 
Here is the link to my repo PR https://github.com/yeshamavani/mavenpublish/pull/2
Done things in a similar way like yours but I am facing this error  

Can I please get some help over this 

![image](https://user-images.githubusercontent.com/83634146/228503488-67f6a6ec-c19d-4eb0-883b-879b11498bb9.png)

**Comment by natansil** [comment]
I'm not sure. I recommend opening an issue directly in Vaticle's repo
